### ISSUE TITLE
Declarations List and Details via Cabinet FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#12]
_From @danakonovalenko on March 16, 2018 13:21_

As an authorized patient after I signed declaration I want to be able view my current declaration and to see history of previous
In order to be able to do such I need to have

 - [x] page with declaration history [spec](https://edenlab.atlassian.net/wiki/x/IAAFGg)
 - [x] page with details of each declaration [spec](https://edenlab.atlassian.net/wiki/x/tAGxGQ)

_Copied from original issue: edenlabllc/ehealth.api#1959_

**Comment by svetavedmed** [comment]
In case patient does not have any active declaration the steps for finding doctor should be shown and declaration history list

**Comment by kiurchv** [comment]
@svetavedmed Ready for testing

**Comment by svetavedmed** [comment]
- [ ] on declaration details
![Screen Shot 2018-06-26 at 15.06.42.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379ea0c2b57415b4cbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb58f64ae5455dac103062f43b.png)
