### ISSUE TITLE
IE11 design fixes

### ISSUE THREAD

**Issue by burlachenkovv** [edenlabllc/ehealth.web#167]
- [x]  (All pages): Logo shifted to the right. 
Screenshots: 
http://joxi.ru/J2b8bM7TXoNM9r
http://joxi.ru/52a7bq4C4vJZXr

- [x] (Home): Declaration header incorrect aligning, Declaration status shifted.
Screenshot: 
http://joxi.ru/Grq4ZOocQ6WokA

- [x] (All pages): Tooltip shown in the button part of the page after mouse over on the user name in the header.
Screenshot:
http://joxi.ru/v296ajZt3LaZ6A

- [x] (Declaration Details): Declaration header incorrect aligning.
Screenshot:
http://joxi.ru/KAx4xGOcMRgdzA

- [x] (Search): Form fields incorrect aligning. Select field's height is bigger than input
Screenshot:
http://joxi.ru/v296ajZt3LMd0A
