### ISSUE TITLE
IE11 fixes

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#181]
- [x] print preview form
![2](https://user-images.githubusercontent.com/30794602/43722159-5a970326-999d-11e8-9bfe-a901d60f5212.jpg)
- [ ] DS does not work
![3](https://user-images.githubusercontent.com/30794602/43722189-65d938da-999d-11e8-8d04-4a6e109004fd.jpg)
- [ ] filter does not work
![5](https://user-images.githubusercontent.com/30794602/43722433-f02a25a8-999d-11e8-8a03-efa7b4d818a7.jpg)
- [x] wrong profile preview
![4](https://user-images.githubusercontent.com/30794602/43722307-a7b2954e-999d-11e8-8062-08919c5ddb23.jpg)
- [x] wrong employee preview
![6](https://user-images.githubusercontent.com/30794602/43722510-16f5e3a2-999e-11e8-94c8-1e1f3e7e4cca.jpg)

**Comment by burlachenkovv** [comment]
- [ ] Need to adapt polyfill library for IE11
