### ISSUE TITLE
Search for a Person 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#285]
As NHS admin I want to be able to find a patient using searching parameters   and to see the grid with info

```
- person_name (first & second & last)
- birth_date
- tax_id
- national_id
- authentification_method
- details
```
child of #263

**Comment by danakonovalenko** [comment]
- [ ] change format for field 'Додано' without `T` and show in our time zone
- [ ] calendar pickup one day earlier 
- [ ] calendar doesn't close 
- [ ] change mask for unzr (yyyymmdd-11111)
- [ ] fix drop-down with additional fields
<img width="362" alt="screen shot 2018-09-28 at 5 57 22 pm" src="https://user-images.githubusercontent.com/31403196/46216392-258f2580-c348-11e8-9d70-2afcd5bf6215.png">
- [ ] there is no `reset changes` possibility
