### ISSUE TITLE
Cabinet Sign Up FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#3]
_From @danakonovalenko on March 16, 2018 9:37_

As a part of oauth develop FE process of registration patients via Cabinet as described in [confluence](https://edenlab.atlassian.net/wiki/x/CoBcFQ)
pages for:
- [x] Send notification email [confluence](https://edenlab.atlassian.net/wiki/x/GIAeGQ)
- [x] Validate Link from Email [confluence](https://edenlab.atlassian.net/wiki/x/JYEfGQ)
- [x] Registration form (MPI/User Create/Update) [confluence](https://edenlab.atlassian.net/wiki/x/uYIeGQ)

_Copied from original issue: edenlabllc/ehealth.api#1950_

**Comment by svetavedmed** [comment]
- [ ] EV3.	input email which already exists.
Expected result - 409 "User with this email already exists"
Actual result - no error
<img width="1440" alt="screen shot 2018-05-10 at 15 23 57" src="https://user-images.githubusercontent.com/30794602/39875657-df99c630-5479-11e8-911d-4050f6236e13.png">

- [ ] EV4	input incorrect email
if error msg = 500, no error is shown
if error msg = 422, no error is shown
<img width="1440" alt="screen shot 2018-05-10 at 17 43 53" src="https://user-images.githubusercontent.com/30794602/39875649-dabebcb0-5479-11e8-9af8-c5dc316874b5.png">

**Comment by svetavedmed** [comment]
- [ ] it would be great to write data format
<img width="435" alt="screen shot 2018-05-11 at 10 54 51" src="https://user-images.githubusercontent.com/30794602/39914842-eb3ff726-550e-11e8-8a20-ffbda877ae50.png">

- [ ] add "адреса реєстрації/проживання"
<img width="474" alt="screen shot 2018-05-11 at 11 32 24" src="https://user-images.githubusercontent.com/30794602/39914947-27e188fc-550f-11e8-92ac-865f80653adf.png">

- [ ] filter does not work
<img width="462" alt="screen shot 2018-05-11 at 11 35 06" src="https://user-images.githubusercontent.com/30794602/39915026-73f8da60-550f-11e8-9375-3253b2f25faf.png">

- [ ] change building format 
<img width="230" alt="screen shot 2018-05-11 at 11 37 02" src="https://user-images.githubusercontent.com/30794602/39915107-bb910320-550f-11e8-9e6d-3fb1d0d1aece.png">

- [ ] it would be great to make more strong email
<img width="498" alt="screen shot 2018-05-11 at 11 54 09" src="https://user-images.githubusercontent.com/30794602/39915999-0dcec56c-5512-11e8-8266-4c4600efaf65.png">

**Comment by svetavedmed** [comment]
- [ ] all phone numbers are not validated
<img width="457" alt="screen shot 2018-05-11 at 11 56 37" src="https://user-images.githubusercontent.com/30794602/39916171-712c61e6-5512-11e8-89fe-723164f8780d.png">

**Comment by svetavedmed** [comment]
- [ ] sms could not be sent - no error
<img width="1440" alt="screen shot 2018-05-11 at 12 39 15" src="https://user-images.githubusercontent.com/30794602/39918187-6e162dd8-5518-11e8-8c54-293c308f69e4.png">

**Comment by svetavedmed** [comment]
- [ ] no error is shown
"message": "document must be signed by 1 signer but contains 0 signatures"

<img width="1440" alt="screen shot 2018-05-11 at 15 11 36" src="https://user-images.githubusercontent.com/30794602/39923847-01f65ce8-552e-11e8-9001-96cca5814c9b.png">

**Comment by svetavedmed** [comment]
- [ ] values entered by user should take precedence over default form values
<img width="530" alt="screen shot 2018-05-11 at 16 20 25" src="https://user-images.githubusercontent.com/30794602/39926249-453d49e0-5537-11e8-9685-f44d13d4ca19.png">

- [ ] after registration on authorization Bearer token is wrong
<img width="1371" alt="screen shot 2018-05-11 at 16 25 01" src="https://user-images.githubusercontent.com/30794602/39926526-22d063a0-5538-11e8-886e-e5a7d8f50683.png">

**Comment by svetavedmed** [comment]
- [ ] error is not shown
<img width="1440" alt="screen shot 2018-05-14 at 14 59 41" src="https://user-images.githubusercontent.com/30794602/39996239-866c3adc-5787-11e8-8c00-3fe328c64cf0.png">

**Comment by svetavedmed** [comment]
- [ ] code do not reseted after returning to the page
<img width="1440" alt="screen shot 2018-05-14 at 15 02 44" src="https://user-images.githubusercontent.com/30794602/39999259-540bb52c-5791-11e8-9e0b-024b77259065.png">

**Comment by svetavedmed** [comment]
<img width="1440" alt="screen shot 2018-05-14 at 17 08 26" src="https://user-images.githubusercontent.com/30794602/40002448-7f3946f8-5799-11e8-8ab9-bd9c2456db9e.png">

**Comment by svetavedmed** [comment]
- [ ] show error - secret is less then 6 symbols
![Screen Shot 2018-05-15 at 16.25.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f66b7191a379e90c2954415c47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ef542e14a5dad17366bf43b.png)

**Comment by svetavedmed** [comment]
- [ ] GU7 - no error
![Screen Shot 2018-05-16 at 13.03.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ec0c2b52415e47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ef24de44d57a0153e6af43b.png)

**Comment by svetavedmed** [comment]
- [ ] register new user for duplicated mpi.person  - no error
![Screen Shot 2018-05-16 at 17.13.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379e80c2a52415f4ebe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ef243e14d51a51a3e65f43b.png)

- [ ] update user with status is_blocked=true - no error
![Screen Shot 2018-05-16 at 17.36.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379e80c2857415f4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ef243e04954a01a3664f43b.png)

**Comment by svetavedmed** [comment]
- [ ] on the creating psw page button works from the second try only

**Comment by svetavedmed** [comment]
- [ ] show error for changing psw for existing user
![Screen Shot 2018-05-16 at 17.41.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379e80c2f50415e4bbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ef243e04a57a417336af43b.png)

**Comment by svetavedmed** [comment]
- [ ] no error
![Screen Shot 2018-05-30 at 15.36.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f36b7191a379ea0c2857415f4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff043e24554a6133e62f43b.png)

- [ ] birthdate is not validated
![Screen Shot 2018-05-30 at 15.43.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f36b7191a379ea0c2f52415d4cbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ff043e54f50a2153562f43b.png)

- [ ] error should be shown
![Screen Shot 2018-05-30 at 16.01.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f36b7191a379e90c2b50415f4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ff043e44e57a015336af43b.png)

**Comment by svetavedmed** [comment]
- [ ] incorrect birth date - show error
![Screen Shot 2018-05-30 at 17.07.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f36b7191a379e80c2b56415d47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ff043e84e54a1163461f43b.png)

**Comment by svetavedmed** [comment]
- [ ] add psw control - two fiels for entering psw

**Comment by kiurchv** [comment]
@svetavedmed Ready for testing
