### ISSUE TITLE
Naming NHS admin panel Contracts

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#345]
On Contract Request list/details Contract list/details must be renamed next fields:
- Контракти  to Договори 
- Перелік контрактів to Перелік договорів
- Запити на контракт to Заяви на укладення договору

**Comment by danakonovalenko** [comment]
on the Contract Details page:
- [ ] Назад до списку заяв -> Назад до списку договорів
- [ ] Статус запиту - > Статус договору 
on the Contract  Request List page 
- [ ] ID договору --> ID заяви (first column and search parameter)
on the Contract  Request Details page 
- [ ] ID договору -> ID заяви на укладення договору
