### ISSUE TITLE
Get Contract Details GraphQL

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#375]
As NHS admin I want to be able to get Contract Details using new admin portal.
So, we need to implement it using graphql
- [x] [confluence](https://edenlab.atlassian.net/wiki/x/MoCeHw) / schema / features / [design](https://marvelapp.com/5e16635/screen/46253154)
- [x] implement 
- [x] test

**Comment by danakonovalenko** [comment]
- [ ] in headers rename `ID запиту` to `ID заяви` 
- [ ] user `databaseId` instead of `name` in DivisionFilter on click `Перейти до працівників` on `Divisions` tab
