### ISSUE TITLE
Email Sign in via Cabinet

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#4]
_From @danakonovalenko on March 16, 2018 9:59_

One of possible options of patients authorization in Cabinet is through input Email/Password and OTP.
Develop FE according to process described [here](https://edenlab.atlassian.net/wiki/x/2IGyGQ)

_Copied from original issue: edenlabllc/ehealth.api#1951_

**Comment by svetavedmed** [comment]
- [ ] fix buttons
![Screen Shot 2018-05-14 at 11.32.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f76b7191a379ee0c2853415f4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ef443e74a5cac1b3f62f43b.png)

**Comment by svetavedmed** [comment]
- [ ] add link "назад"

**Comment by svetavedmed** [comment]
- [ ] error description
<img width="1440" alt="screen shot 2018-05-14 at 18 08 10" src="https://user-images.githubusercontent.com/30794602/40005947-de4e3196-57a1-11e8-8b8a-da8c2103b74f.png">

**Comment by svetavedmed** [comment]
- [ ] error description
<img width="1440" alt="screen shot 2018-05-14 at 18 11 42" src="https://user-images.githubusercontent.com/30794602/40006158-57027d72-57a2-11e8-973b-f4c96b164cc7.png">

**Comment by svetavedmed** [comment]
- [ ] SU14 - no error
<img width="1440" alt="screen shot 2018-05-16 at 17 55 08" src="https://user-images.githubusercontent.com/30794602/40124967-61dfaa6c-5932-11e8-81fd-80370781a939.png">

**Comment by svetavedmed** [comment]
- [ ] add "Назад"
![Screen Shot 2018-05-25 at 17.11.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a379e80c2a50415a4cbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff44ee64853a3123367f43b.png)

**Comment by svetavedmed** [comment]
- [ ] In case factor is null and authentication_factors.is_active=true invoke Init User authentication factor
After authentication_factor was approved it should be redirected to Cabinet
![Screen Shot 2018-05-25 at 17.42.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a379e80c2f53415f4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff44ee84953ad103661f43b.png)

**Comment by svetavedmed** [comment]
- [ ] show error description
repo steps - enter wrong client_id (ex. http://auth.dev.asclepius.com.ua/otp-send?client_id=30074b6e-fbab-4dc1-9d37-88c21dab1840&redirect_uri=http%3A%2F%2Fexample2.com&scope=)
![Screen Shot 2018-05-25 at 18.00.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a379e70c2b51415d49be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff44de14855ac1b3e65f43b.png)

**Comment by svetavedmed** [comment]
- [ ] Sign In existing user without 2FA
actual result - 200 and error msg - У даного користувача не має доступу
expected result - 403   "message": "REQUEST_LOGIN_VIA_DS"
back works correct from Postman, but front behaviour is defferent

**Comment by ivchenkodima** [comment]
@svetavedmed please test this case one more. The back Button in near Changing OTP Link.
<img width="1440" alt="2018-05-25 19 21 51" src="https://user-images.githubusercontent.com/8415813/40555222-09300f12-6051-11e8-861d-16f758e1437b.png">

**Comment by lymychp** [comment]
@ivchenkodima please update status

**Comment by ivchenkodima** [comment]
blocked by https://github.com/edenlabllc/ehealth.api/issues/2524
