### ISSUE TITLE
Legal entity list page bugs and enhancement

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#401]
- [x] instead of `id` must be `databaseID`
- [x] `address` must be separated by rows
- [x] `додано` should be hidden by default
- [ ] column with for edrpou I status should be less
- [x] rename `показати деталі` --> `деталі` (and column should be more narrow)
- [x] додано - split on 2 rows - date and time
- [x] verified/not verified must be centered
- [x] rename `Додати показник` to `Додати параметр`
- [ ] show possibilities for page size 
- [ ] clicking on button `скинути поточні налаштування` should change current settings. as for now settings are changed each time after clicking on sorting column
