### ISSUE TITLE
Legal entity pages bugs and enhancement 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#411]
`https://admin.dev.asclepius.com.ua/legal-entities/TGVnYWxFbnRpdHk6NDFlYmFlNWUtYzI2OS00OTFmLTlmNzgtMDViZmRhZTVlMzk3`
- [x] there is no `address` for legal entity on `general_info` tab
- [x] nhsVerified and misVerified should be darker
<img width="293" alt="screen shot 2018-10-23 at 9 50 38 pm" src="https://user-images.githubusercontent.com/31403196/47383628-c4bbf880-d70d-11e8-9fcb-f9657ddbb356.png">

-  [x] in case boolean=false indicator also must be shown (mountain_region, nhs/mis verified)
-  [x] order by for related legal entities: INSERTED_AT_ASC, INSERTED_AT_DESC, IS_ACTIVE_ASC, IS_ACTIVE_DESC
- [ ] tabs should fit in one row
<img width="749" alt="screen shot 2018-10-23 at 10 16 11 pm" src="https://user-images.githubusercontent.com/31403196/47384920-511bea80-d711-11e8-9950-4f31fa1f9a74.png">

**Comment by danakonovalenko** [comment]
on `legal-entities/search` page
- [ ] remove form autosubmit edrpou field 
- [ ] add icon for nhs_verified=false

on `related legal entity tab`
- [ ] move `Додати підпорядкований мед заклад` above input filter

on first step of `legal entity merge`
- [ ] do not show result until submit edrpou
- [ ] add icon for nhs_verified=false

on `legal entity job` page
- [ ] do not show execution time if the job in status='PENDING'

**Comment by danakonovalenko** [comment]
- [ ] filter by division name on Legal entity page division tab doesn't work
