### ISSUE TITLE
Manage dictionaries chapter

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#426]
- [x] add page to update dictionairies 
- [x] test

**Comment by danakonovalenko** [comment]
- [ ] add icons for deactivated dictioanaries
![Screen Shot 2018-12-13 at 5.13.02 PM.png](https://zube.io/files/edenlabllc/e70ccc2a9e74919f7e2515ad75ba2a1b-screen-shot-2018-12-13-at-5-13-02-pm.png)
- [ ] do not allow to delete all tags and values (in case there is only one tag/value left it's shouldn't be allowed to delete it)
- [ ] on dictionaries list page change input for tags to input with drop-down (as it's on update page)
