### ISSUE TITLE
LE approve new. GraphQL

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#463]
design
- [x] design

new
- [x] add mutations
   - nhs_review = true and nhs_review = false
   - nhs_verified = false

changes
- [x] add more fields to LE
- [x] add more fields to owner
- [x] change get LE by nhs' add new fields 
   - comment
   - nhs review with filters
- [x] logic for verify LE by NHS
   - do not permit verify before review = true
   - add comments for verify
- [x] logic for Le decline
   - decline with comments
   - do not decline before nhs_review true

**Comment by svetavedmed** [comment]
- [ ] add nhsReview to get LE list with ordering nhsReview_ASC, nhsReview_DESC [PR](https://github.com/edenlabllc/ehealth.web/pull/507/files)
- [ ] change date format to UKR
- [ ] add symbol limit to comment

**Comment by burlachenkovv** [comment]
`ordering nhsReview_ASC, nhsReview_DESC` blocked by BE
