### ISSUE TITLE
Contract Demo Comments

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#495]
Contract Request detail page
- [x] show `status_reason` in case it's not empty
- [x] add previous_request.databaseId as link to ContractRequest
- [x] add block about NHS on general tab with fields
  - Ім'я підписанта - nhsSigner.party.firstName&SecondName...
  - nhsSignerBase
  - paymentMethod 
  - issueCity

Update Contract Request
- [x] allow nhsContractPrice = 0

Contract detail page
- [x] show `status_reason` after terminate step 
- [x] add prinoutForm `Дивитись друковану форму`
       contract.contractRequest.printoutForm
- [x] show finally signed content -  blocked by  #3535
- [x] Rename `Призупинений` в `Стан договору  with enum `Діючий/Призупинений/Всі`. 

Printout form 
- [x] delete limit column from appendex2

**Comment by danakonovalenko** [comment]
On Contract Request Details Page
- [ ] on `Медзаклад` tab make `ID медзакладу` as link with lead to LegalEntity Details page
- [ ] define and set values on Update Contract Request page
   - issue_city - Київ
   - nhs_signer - Петренко Олег Едуардович
   - base - `Положення про Національну службу здоров'я України, затвердженого постановою Кабінету Міністрів України від 27 грудня 2017 року № 1101`
   - payment_method - BACKWARD 
- [ ] tamplate
   - delete header and footer
   - delete column `штатна одиниця`
   - delete text `ЗАТВЕРДЖЕНО постановою Кабінету Міністрів України від 25 квітня 2018 р. No 410`
   - change approve_text to 
[Повідомлення про намір.docx](https://github.com/edenlabllc/ehealth.web/files/2595328/default.docx)
