### ISSUE TITLE
DS Sign in via Cabinet

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#5]
_From @danakonovalenko on March 16, 2018 10:2_

In case patients doesn't have set 2FA factor there is a way to authorize in Cabinet using DS and password to DS.
Develop FE process according to the [process](https://edenlab.atlassian.net/wiki/x/bQB5Gw)

_Copied from original issue: edenlabllc/ehealth.api#1952_

**Comment by svetavedmed** [comment]
- [ ] add link "увійти за допомогою email"
https://api.media.atlassian.com/file/373841bc-888c-4e0f-b6dc-4e472f386505/image?mode=full-fit&client=98e9237f-049d-4395-b7dc-36da84edcfec&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5OGU5MjM3Zi0wNDlkLTQzOTUtYjdkYy0zNmRhODRlZGNmZWMiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjM3Mzg0MWJjLTg4OGMtNGUwZi1iNmRjLTRlNDcyZjM4NjUwNSI6WyJyZWFkIl19LCJleHAiOjE1MjYzMDcxMjcsIm5iZiI6MTUyNjMwMzc2N30.zIPBtqlS6Lv01MuORsNEKYjhxSHMJqAfTSB3bIk4sM8

**Comment by svetavedmed** [comment]
- [ ] add error description
<img width="1440" alt="screen shot 2018-05-14 at 17 47 02" src="https://user-images.githubusercontent.com/30794602/40004678-dd68daa4-579e-11e8-8297-fa278b4e6cbb.png">

- [ ] add error description
repo steps
1. add DS
2. wrong psw
3. click to red error
4. cansel
5. correct psw
<img width="498" alt="screen shot 2018-05-14 at 17 48 16" src="https://user-images.githubusercontent.com/30794602/40004823-2e822a9e-579f-11e8-8f90-3c39f786469f.png">

**Comment by svetavedmed** [comment]
- [ ] sign in with wrong DS - no error 
![Screen Shot 2018-05-18 at 10.36.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455fb6b7191a379ef0c2857415f4abe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ef049e84d52a0123f64f43b.png)

**Comment by svetavedmed** [comment]
![Screen Shot 2018-05-21 at 16.13.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379e90c2a52415c48be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5eff4be9495ca4113e60f43b.png)

**Comment by svetavedmed** [comment]
- [ ] no error description while signing in with wrong redirect uri
![Screen Shot 2018-05-25 at 18.53.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f66b7191a379e70c2e52415d47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff44de24b5ca5163763f43b.png)

**Comment by svetavedmed** [comment]
- [ ] no error
user does not have global_roles
![Screen Shot 2018-05-29 at 11.54.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fa6b7191a379ee0c2e55415b49be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff343e54c53a5143561f43b.png)

**Comment by svetavedmed** [comment]
- [ ] back msg = message:"User blocked", but front = Упс. Щось пішло не так. Повторіть спробу пізніше
[Uploading Screen Shot 2018-05-29 at 14.05.16.png...]
