### ISSUE TITLE
Admin Panel v.2 for Capitation Contacts v.3

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.web#502]
- [x] Contract Request list GraphQL parent of edenlabllc/ehealth.web#368  
- [x] Get Contract Request Details GraphQL parent of edenlabllc/ehealth.web#369  
- [x] Assign Contract Request GraphQL parent of edenlabllc/ehealth.web#370  
- [x] Update and Approve Contract Request GraphQL parent of edenlabllc/ehealth.web#371  
- [x] Approve Contract Request GraphQL  parent of edenlabllc/ehealth.web#372  
- [x] Decline Contract Request GraphQL parent of edenlabllc/ehealth.web#373  
- [x] Sign Contract Request GraphQL parent of edenlabllc/ehealth.web#374

- [x] Get Contract Details GraphQL parent of edenlabllc/ehealth.web#375  
- [x] Get Contract List GraphQL parent of edenlabllc/ehealth.web#376  
- [x] Terminate Contract GraphQL parent of edenlabllc/ehealth.web#377  
- [x] Digital Stamp parent of edenlabllc/ehealth.web#378

**Comment by danakonovalenko** [comment]
improvement / bug fixing 
- [ ] Contract Demo Comments parent of #495 
- [ ] Combine both Admins parent of 483
