### ISSUE TITLE
Merge Legal entities Process

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#503]
- [x] Get children legal entity by NHS parent of edenlabllc/ehealth.web#321  
- [x] Create related legal entities parent of edenlabllc/ehealth.web#322

- [x] LE merged jobs parent of edenlabllc/ehealth.web#326  
- [x] LE details for reorganized legal entities parent of edenlabllc/ehealth.web#430

**Comment by danakonovalenko** [comment]
- [ ] Prolongate contract mutation parent of #460
