### ISSUE TITLE
LE approve new. fixes after UAT

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#597]
- [x] change green check mark to yellow
- [x] add comment text next to comment link
- [x] change "розглянутий нсзу" to "опрацьовано" on get legal_entity list
