### ISSUE TITLE
Add GraphQL back for decalrations/persons

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#615]
Instead of using mocks we should add implemented back services for:
- [x] type Persons [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/persons.graphql)
- [x] type declarations [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/declarations.graphql)
- [x] mutation `resetPersonAuthenticationMethod`

**Comment by danakonovalenko** [comment]
- [ ] in case I put data, then delete it the error with filters occurs
![image](https://user-images.githubusercontent.com/31403196/51571404-edf83c00-1e56-11e9-8b1f-712142e36ed4.png)
- [ ] if i manually input data and do not choose it from calendar date in calendar and date in input field doesn't match each other
![image](https://user-images.githubusercontent.com/31403196/51571506-2861d900-1e57-11e9-8689-5ec8c4100f59.png)
- [ ] I can't reset phone number once I already filled it. So, if I filled the number and then delete it I see the error 
![image](https://user-images.githubusercontent.com/31403196/51571561-58a97780-1e57-11e9-8360-2744b41aed90.png)
- [ ] in case I fill phone number, then delete it and fill birthdate SEARCH button is still disabled
- [ ] there is no regular expression for field PASSPORT 
- [ ] please, add column status to grid with possibility to order by it

**Comment by danakonovalenko** [comment]
as for now any number I fill in field passport number returns me an error `Невірний номер`.

**Comment by burlachenkovv** [comment]
![unzr.png](https://zube.io/files/edenlabllc/5d521e86ca9d19b742b7f8c3dc7af4fb-unzr.png)![unzr.png](https://zube.io/files/edenlabllc/5d521e86ca9d19b742b7f8c3dc7af4fb-unzr.png)

Mask for the passport contains 2 Cyrillic symbols + 6 numbers: АЯ123456.
Mask for the unzr contains 13 numbers with format 11111111-11111.

**Comment by burlachenkovv** [comment]
![unzr.png](https://zube.io/files/edenlabllc/5d521e86ca9d19b742b7f8c3dc7af4fb-unzr.png)![pass.png](https://zube.io/files/edenlabllc/434675c5abdfcec1d6460fcc0cf8998f-pass.png)

UNZR mask contains 13 numbers, format: 11111111-11111
Passport mask contains 2 cyrillic symbols + 6 numbers: АЯ123456
