### ISSUE TITLE
Sign-up crowd testing results 

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.web#62]
- [x] date controls should use `.` separator, not `\`
![image](https://user-images.githubusercontent.com/5257001/40768958-6e1628e0-64bf-11e8-94c2-c3cd8dd98270.png)
- [x] валідація для міста народження - we should use the same regexp as for API
![image](https://user-images.githubusercontent.com/5257001/40769033-9feb76d6-64bf-11e8-918b-03bf2e32f24a.png)
- [x] failed to pass otp validation
![image](https://user-images.githubusercontent.com/5257001/40769667-4237b570-64c1-11e8-9a6e-6fe752574f61.png)
```
{
  "meta": {
    "url": "http://api-svc.il/api/cabinet/registration",
    "type": "object",
    "request_id": "e9520d7b-eaed-4698-a50b-580e3b4895e4#2873",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "invalid",
            "params": [],
            "description": "invalid code"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.otp"
      }
    ]
  }
}
```
