### ISSUE TITLE
Find Doctor/Clinic FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#7]
_From @danakonovalenko on March 16, 2018 10:27_

Authorized user must be able to 
- [x] [find divisions](https://edenlab.atlassian.net/wiki/x/GgAMDg) by searching parameters (list and details page)
- [x] [find doctors](https://edenlab.atlassian.net/wiki/x/zgNtGQ) by searching parameters (list and details page)
- find division on map (map and details page) #41

_Copied from original issue: edenlabllc/ehealth.api#1954_

**Comment by svetavedmed** [comment]
- [ ] Getting CORS error on the search page: ```Failed to load https://api.dev.asclepius.com.ua/api/uaddresses/settlements?name=&page=1&page_size=20: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://account.dev.asclepius.com.ua' is therefore not allowed access.```

**Comment by kiurchv** [comment]
@svetavedmed Ready for testing

**Comment by ephor** [comment]
@svetavedmed fix bug with region

**Comment by svetavedmed** [comment]
- [ ] sometimes there is no region
![Screen Shot 2018-06-26 at 16.32.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379e90c2853415e47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb58f649e14c54a61a3564f43b.png)

**Comment by ephor** [comment]
@svetavedmed Fix map. Ready for test
