### ISSUE TITLE
View/Update Personal Info

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#8]
_From @danakonovalenko on March 16, 2018 11:20_

As authorized in cabinet patient I want to be able to see my current personal information and update it in case if it's needed.
In order to be able to do it there must be pages:
- [x] view current personal info [spec](https://edenlab.atlassian.net/wiki/x/XAIoGg)
- [x] update (available to update) fields [spec](https://edenlab.atlassian.net/wiki/x/XwCDG)

_Copied from original issue: edenlabllc/ehealth.api#1955_

**Comment by kiurchv** [comment]
@svetavedmed Deployed on dev and ready for testing

**Comment by svetavedmed** [comment]
- [ ] can't change City
![Screen Shot 2018-06-26 at 15.31.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379ea0c2850415d47be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb58f64ae74e51a1163260f43b.png)
- [ ] space should be allowed
![Screen Shot 2018-06-26 at 15.33.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379ea0c2852415f46be5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb58f64ae74954a6153264f43b.png)
- [ ] Бажаний метод зв’язку should be in Ukrainian
![Screen Shot 2018-06-26 at 15.39.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379ea0c2858415e4bbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb58f64ae74a52a0173261f43b.png)

**Comment by kiurchv** [comment]
> Бажаний метод зв’язку should be in Ukrainian

@svetavedmed We need the dictionary with possible contact method values to achieve this
