### ISSUE TITLE
Get Contract by ID

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#83]
As NHS Admin I want see details of each contract through admin portal
[spec](https://edenlab.atlassian.net/wiki/x/MoCeHw)
[apiary](https://uaehealthapi.docs.apiary.io/reference/contracts/contracts/get-contract-details)

**Comment by svetavedmed** [comment]
- [ ] "Назад до списку запитів" from Contract details page doesn't work properly
- [ ] Get contracts list filtered by page return different amount of contracts, ex. page=2 two contracts, page=6 only one. Should be the same number of contracts each page = 5,20,50
- [ ] "Детально" doesn't work for some contracts with no error, ex contract_id='466635b9-9cba-4a89-9c47-29ccab30249a'
- [ ] after searching contract list by id filter does not want to be reseted 
- [ ] in case nothing found "NO DATA" should be in Ukrainian

**Comment by danakonovalenko** [comment]
- [ ] boolean filed is_suspended (призупинений) is missing from details
