### ISSUE TITLE
Contract list

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#84]
As NHS Admin I want see list of contacts through  Admin portal
[spec](https://edenlab.atlassian.net/wiki/x/YoCIHw)
[apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-get-contracts-list)

**Comment by svetavedmed** [comment]
- [ ] "Назад до списку запитів" from Contract details page doesn't work properly
- [ ] Get contracts list filtered by page return different amount of contracts, ex. page=2 two contracts, page=6 only one. Should be the same number of contracts each page = 5,20,50
- [ ] "Детально" doesn't work for some contracts with no error, ex contract_id='466635b9-9cba-4a89-9c47-29ccab30249a'
- [ ] after searching contract list by id filter does not want to be reseted 
- [ ] in case nothing found "NO DATA" should be in Ukrainian

**Comment by ephor** [comment]
@svetavedmed Ready for test. All done except "Data are not validated". I need another task for this.

**Comment by svetavedmed** [comment]
- [ ] "скинути пошук" doesn't work for pages

**Comment by ephor** [comment]
@svetavedmed Done

**Comment by danakonovalenko** [comment]
- [ ] boolean filed is_suspended (призупинений) is missing from filters and grid
