### ISSUE TITLE
Reset authentication method mutation. FE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#979]
#### Description

NHS request to reset auth_method via file, as there are involved two department in this process so the first one will look for persons and the second one with necessary scopes will download file and reset auth phone number for those persons

[Zube #6284](https://zube.io/edenlabllc/e-health/c/6284)  

#### Context

As NHS Admin I want to load file in Admin Panel with person_ids and reset auth_method to these persons, so that it make my work faster

#### What changes

persons. Auth method should be reseted for persons in .csv file

#### Possible Implementation

- add page with file uploading
- file uploading, validations and error
- redirect to jobs page

#### Documentation, Adoption

1. [Confluence](https://edenlab.atlassian.net/wiki/spaces/EH/pages/344031370/AUTO+Terminate+declaration)
2. [Apiary or Schema](https://uaehealthapi.docs.apiary.io/#reference/internal.-nhs-admin/uploading-and-processing-registers/create/update-legal-entity-v2)

**Comment by svetavedmed** [comment]
- [ ] block button "Скинути метод аутентифікації" if file wasn't uploaded

**Comment by svetavedmed** [comment]
- [ ] reset error list on uploading new .csv file

**Comment by svetavedmed** [comment]
- [ ] in case error in file is empty string - i do not see it in error list 
![Screen Shot 2019-06-25 at 6.43.37 PM.png](https://zube.io/files/edenlabllc/357db7930cfd2ab4293fc0c3fdb1f620-screen-shot-2019-06-25-at-6-43-37-pm.png)

**Comment by svetavedmed** [comment]
- [ ] pagination does not work properly
